### ISSUE TITLE
Release plan for 2.0.0

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1047]
## Checklist for release 2.0.0-beta.10 and subsequently 2.0.0

* [x] ignite-i18n update merged https://github.com/infinitered/ignite-i18n/pull/7
* [x] ignite-vector-icons update merged https://github.com/infinitered/ignite-vector-icons/pull/6
* [x] ignite-animatable update merged https://github.com/infinitered/ignite-animatable/pull/6
* [x] ignite-ir-next ejs update merged https://github.com/infinitered/ignite-ir-next/pull/54
* [x] ignite-ir-next skip git init merged https://github.com/infinitered/ignite-ir-next/pull/53
* [x] ignite-ir-next refine the walkthrough process https://github.com/infinitered/ignite-ir-next/issues/31 
* [x] ignite-ir-next better success message https://github.com/infinitered/ignite-ir-next/pull/55
* [x] ignite-ir-next pin plugin versions https://github.com/infinitered/ignite-ir-next/issues/57
* [x] ignite overwrite flag https://github.com/infinitered/ignite/pull/1049
* [x] release ignite-dev-screens 2.0.0
* [x] release ignite-i18n 1.0.0
* [x] release ignite-vector-icons 1.0.0
* [x] release ignite-animatable 1.0.0
* [x] release ignite-standard 1.0.0
* [x] *discuss and settle on a good strategy for boilerplate-2 release*
* [x] release ignite-ir-boilerplate 2.0.0-rc.1
* [x] fix sporking issue https://github.com/infinitered/ignite/issues/1043 (pending PR #1056)
* [x] point Ignite CLI master to boilerplate-2 by default (pending PR #1057)
* [x] release ignite CLI 2.0.0-rc1
* [x] release ignite CLI 2.0.0 and ir-boilerplate 2.0.0
* [x] release Jamon's blog post (may need freshening)

**Comment by skellock** [comment]
I did the release notes first, but github won't let me save a new release it until I give it a tag.

Soo.... gonna park this here until I do that!

# 2.0.0-beta.10

## :tada: Features
* `ignite add` now enforces version numbers - so we don't break for semver incompatibilites in the future. #1053, #1054 by @jamonholmgren
* Boilerplates must now include a React Native target version so things accidently break on new releases. #1014 by @fvonhoven
* `ignite new` has a new flag `--overwrite` which will forceable clobber the destination directory. #1049 by @jamonholmgren
* Improves bootup speed. #1012 by @jamonholmgren

## :hammer: Fixes
* Prevents new projects from being called ignite. #1023 by @fvonhoven
* `ignite spork` works again. #1056 by @jamonholmgren
* `.ejs` extension were being left on plugin examples. #1055, #1048 by @jamonholmgren
* Relative paths are properly passed from boilerplates to plugins. #1022 by @jamonholmgren
* Tidies up missed template tokens with `ignite plugin new`. #1019 by @jamonholmgren
* `yarn` was bombing on Windows when the path had spaces. #1010 by @kevinvangelder

## :book: Docs
* Corrects link to the nativebase boilerplate. #1033 by @tristola
* Shows the command for adding a different boilerplate. #1031 by @aaafly
* Fixes our poor grammar. #1030 by @raviqqe

## :ambulance: Support
* Default boilerplate is now `ir-boilerplate@2.0.0`. Previously known as `ir-next`. RIP `ir-boilerplate-2016`. #1057 by @jamonholmgren
* Bumps dependencies. #1041, #1046 by @jamonholmgren, @skellock
* Adds `np` for shipping builds. #1041 by @jamonholmgren
* Typing `ignite <something> --verbose` will tell you to run `ignite <something> --debug`. #1039 by @jamonholmgren
* Adds deprecation warning when omitting .ejs extension on templates in generators. #1038 by @jamonholmgren
* Removes the codacy badge. #1025 by @skellock
* Shows a warning when adding a version-less plugin from a path. #1021 by @jamonholmgren
* Resurrects the end-to-end CI script. #1011 by @jamonholmgren
* Removes `lerna` as this is now a 1 project kinda repo. #1009 by @jamonholmgren

**Comment by jamonholmgren** [comment]
Released! :tada:
